server:
  port: 9000



spring:
  datasource:
    url: jdbc:postgresql://192.168.0.53:5432/user_registration
    password: root22!
    driver-class-name: org.postgresql.Driver
    username: root
  jpa:
    show-sql: true
  flyway:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    enabled: true
    user: ${spring.datasource.username}
  session:
    jdbc:
      initialize-schema: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
tsm:
  auth-server:
    server-auth-url: http://127.0.0.1:9000
